version: '3'

volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:

  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data

  backend:
    image: agvostrikova/foodgram_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
      - media_volume:/media/
    depends_on:
      - db
  frontend:
    image: agvostrikova/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static

  nginx:
    image: agvostrikova/foodgram_nginx
    env_file: .env
    volumes:
      - static_volume:/staticfiles
      - media_volume:/media/
    ports:
      - 8080:80
    depends_on:
      - backend