# Generated by Django 3.2.3 on 2024-07-09 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'verbose_name': 'Список ингредиентов', 'verbose_name_plural': 'Списки ингредиентов'},
        ),
    ]
